services:
  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - public-data:/rails/public
      - tmp-data:/rails/tmp
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    env_file:
      - .env
    volumes:
      - public-data:/rails/public
      - tmp-data:/rails/tmp
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  public-data:
  tmp-data:
